server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  groovy:
    template:
      suffix: .groovy
      cache: false
      configuration:
        auto-new-line: true
        auto-indent: true